library(plyr)
library(ggplot2)
library(reshape2)

setwd("~/GitHub/HomeCode")
veh = read.csv("data\\vehicles.csv", stringsAsFactors = FALSE, sep = ",", na.strings = "")
dim(veh)
head(veh)
unique(veh$trany)
names(veh)
length(unique(veh$year))
first_year = min(veh$year)
last_year = max(veh$year)
barplot(table(veh$fuelType1))
veh$trany2 = ifelse(substr(veh$trany, 1, 4) == "Auto", "Auto", "Manual")
